export const tablesCargaInicial = [
  { code: 'T01' },
  { code: 'T02' },
  { code: 'T03' },
  { code: 'T04' },
  { code: 'T05' },
  { code: 'T06' },
  { code: 'T07' },
  { code: 'T08' },
  { code: 'T09' },
  { code: 'T10' },
  { code: 'T11' },
  { code: 'T12' },
  { code: 'T13' },
  { code: 'T14' },
  { code: 'T15' },
  { code: 'T16' },
  { code: 'T17' },
  { code: 'T18' },
  { code: 'T19' },
  { code: 'T20' },
];
